site_name: ome-zarr-models
site_url: https://ome-zarr-models-py.readthedocs.io
theme:
  name: material

markdown_extensions:
  - toc:
      toc_depth: 3

plugins:
  - mkdocs-jupyter:
      execute: true
      allow_errors: false
  - mkdocstrings:
      handlers:
        python:
          paths: [src]
          import:
            - https://docs.python.org/3/objects.inv

          options:
            docstring_style: numpy
            show_root_toc_entry: false
            show_object_full_path: true
            group_by_category: true
            heading_level: 3
            show_symbol_type_heading: true
            separate_signature: true
            show_source: false
            show_signature_annotations: true
            signature_crossrefs: true
            extensions:
              - griffe_pydantic:
                  schema: false

nav:
  - Tutorial: tutorial.py
  - API reference:
      - v04:
          - api/v04/datasets.md
          - api/v04/metadata.md
  - Contributing: contributing.md

watch:
  - src
