site_name: ome-zarr-models
site_url: https://ome-zarr-models-py.readthedocs.io
theme:
  name: material
  features:
    - navigation.tabs

plugins:
  - mkdocs-jupyter:
      execute: false
      allow_errors: true
  - mkdocstrings:
      handlers:
        python:
          paths: [src]
          options:
            docstring_style: numpy
            parameter_headings: true
            show_root_toc_entry: false
            show_object_full_path: true
            group_by_category: true
            heading_level: 3
            show_symbol_type_heading: true
            show_source: false
            separate_signature: true
            show_signature_annotations: true
            signature_crossrefs: true

nav:
  - Tutorial: tutorial.py
  - Contributing: contributing.md
  - API reference:
      - v04:
          - api/v04/top_level.md
          - api/v04/other.md

watch:
  - src
