site_name: ome-zarr-models
site_url: https://ome-zarr-models-py.readthedocs.io
theme:
  name: material

plugins:
  - mkdocs-jupyter:
      execute: true
      allow_errors: true
  - mkdocstrings:
      handlers:
        python:
          options:
            docstring_style: numpy

nav:
  - Tutorial: tutorial.py
  - api.md
