site_name: ome-zarr-models
site_url: https://ome-zarr-models-py.readthedocs.io
theme:
  name: material

plugins:
  - mkdocstrings:
      handlers:
        python:
          options:
            docstring_style: numpy

nav:
  - index.md
  - api.md
