[project]
name = "ome-zarr-models"
dynamic = ["version"]
description = "Data models for OME-Zarr"
readme = "README.md"
requires-python = ">=3.10"
dependencies = []

[tool.hatch.version]
source = "vcs"

[build-system]
requires = ["hatchling", "hatch-vcs"]
build-backend = "hatchling.build"

[dependency-groups]
docs = ["mkdocs>=1.6.1", "mkdocstrings-python>=1.12.2"]

[tool.uv]
default-groups = ["docs"]
