[project]
name = "ome-zarr-models"
dynamic = ["version"]
description = "Data models for OME-Zarr"
readme = "README.md"
requires-python = ">=3.10"
dependencies = []

[tool.hatch.version]
source = "vcs"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[dependency-groups]
docs = ["mkdocs>=1.6.1"]
